bcgov/fams3

README.md
app/SearchApi/SearchApi.Web/Controllers/WeatherForecastController.cs
app/SearchApi/SearchApi.Web/Program.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchApi.Web/WeatherForecast.cs
app/SearchApi/SearchApi.Web/appsettings.Development.json
app/SearchApi/SearchApi.Web/appsettings.json
app/SearchApi/SearchApi.sln

This pr includes the following changes:
* initial `dotnet core 3` search api2

Initial dotnet core web api

---

README.md
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
app/SearchApi/SearchApi.Web/Startup.cs

This pr includes the following changes:
* add `health` endpoint

Add service health endpoints

---

README.md
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web.Test/SearchApi.Web.Test.csproj
app/SearchApi/SearchApi.Web/Configuration/RabbitMqConfiguration.cs
app/SearchApi/SearchApi.Web/People/ExecuteSearch.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchApi.Web/appsettings.json
app/SearchApi/docker-compose.yml

* `ExcuteSearch` contract
* `MassTransit` configuration to push messages

Pushing Execute Search

---

README.md
openshift/.pipeline/Jenkinsfile
openshift/templates/pipeline.bc.yaml
openshift/templates/rabbitmq.dc.yaml
openshift/templates/searchapi.bc.yaml
openshift/templates/searchapi.dc.yaml
sonar-project.properties

This PR introduces a continuous deployment pipeline to FAMS3, building the SearchApi project and deploying to our 'dev' namespace.

Init CICD Pipeline - SearchApi

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Added PR template

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/MatchFound/MatchFoundControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/MatchFound/MatchFoundController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs

Create new post endpoint in dynamics adapter to receive match found events.
Tested with Postman to post MatchFoundResponse to this endpoint.
this PR fixes jira ticket: **FAMS-599**

Create new post endpoint in dynamics adapter to receive match found events

---

README.md
app/SearchApi/SearchApi.Web.Test/Configuration/SearchApiOptionsTest.cs
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierTest.cs
app/SearchApi/SearchApi.Web.Test/Search/MatchFoundConsumerTest.cs
app/SearchApi/SearchApi.Web.Test/SearchApi.Web.Test.csproj
app/SearchApi/SearchApi.Web.Test/Utils/LoggerUtils.cs
app/SearchApi/SearchApi.Web/Configuration/SearchApiOptions.cs
app/SearchApi/SearchApi.Web/Keys.cs
app/SearchApi/SearchApi.Web/Notifications/ISearchApiNotifier.cs
app/SearchApi/SearchApi.Web/Notifications/ServiceCollectionExtensions.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifier.cs
app/SearchApi/SearchApi.Web/Search/MatchFoundConsumer.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchApi.Web/appsettings.json

This PR includes the following proposed changed:
* a webhook system to create a publish subscribe model using REST interface.
Locally using docker.
this PR fixes jira ticket: **FAMS3-594**

Feature/search api/match found webhooks

---

app/SearchApi/SearchAdapter.ICBC.Test/SearchRequest/IcbcMatchFoundBuilderTest.cs
app/SearchApi/SearchAdapter.ICBC/SearchRequest/IcbcMatchFoundBuilder.cs
app/SearchApi/SearchAdapter.ICBC/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core/Adapters/Contracts/MatchFound.cs
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierTest.cs
app/SearchApi/SearchApi.Web/Search/MatchFoundConsumer.cs

This Pr includes the following proposed change
- modification of the `MatchFound` contract to have a new id member
this PR fixes jira ticket: **FAMS3-616**

Adapters must return the SearchRequest ID

---

app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierTest.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifier.cs

This PR includes the following proposed changed:
- Fix when the path contain multiple elements

fixed bug with webHooks uri

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/Models/SSG_SearchApiRequest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestService.cs

for fams-452(change from SearchRequest to SearchApiRequest)
Tested locally
- [ X] My code follows the style guidelines of this project
this PR fixes jira ticket: #FAMS-632

for fams-632(change from SearchRequest to SearchApiRequest)

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/FakeMessages/FakeHttpMessageResponse.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/StatusReasonHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Health/StatusReasonHealthCheck.cs

This PR includes the following changes:
- fix for the health check status
Locally with docker and dynamics connection

fixing issue with healthcheck

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Keys.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs

This pr includes the following changes:
- When the searchApi aknowledge the search, the searchApiRequest is marked `in progress`
dynamics screenshot
this PR fixes jira ticket: **FAMS3-588**

Feature/search api request/update status

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/MatchFound/MatchFoundControllerTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

This pr includes the following changes:
- fix for the failing unit test
Run unit test on Visual Studio

fixed unit tests

---

app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs

This PR includes the following change:
* fix issue with enum
Locally with docker

fixed issue with enum

---

.github/labeler.yml
.github/workflows/label.yml

- new workflow to tag PR based on changes
No Test

Added label action for github

---

app/DynamicsAdapter/DynamicsAdapter.Web/MatchFound/MatchFoundController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/InformationSourceType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Keys.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Read Identifiers for Search Api from Dynamics
tested on my local pc
this PR fixes jira ticket: FAMS-737

Read Identifiers for Search Api from Dynamics

---

app/SearchApi/SearchAdapter.ICBC.Test/SearchAdapter.ICBC.Test.csproj
app/SearchApi/SearchAdapter.ICBC.Test/SearchRequest/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.ICBC.Test/SearchRequest/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.ICBC/SearchAdapter.ICBC.csproj
app/SearchApi/SearchAdapter.ICBC/SearchRequest/PersonSearchRejectedEvent.cs
app/SearchApi/SearchAdapter.ICBC/SearchRequest/PersonSearchValidator.cs
app/SearchApi/SearchAdapter.ICBC/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchAdapter.ICBC/Startup.cs
app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchRejected.cs
app/SearchApi/SearchApi.Core/Adapters/Models/ValidationResult.cs

- A new `PersonSearchRejected` Event to inform `SearchApi` of rejected events
- Implementation of validation for Fake `ICBC Adapter` using [fluentValidation.net](https://fluentvalidation.net/)
this PR fixes jira ticket: **FAMS3-777**

Publish a new validation message when request is received

---

README.md
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
docker-compose.yml

This pr includes the following proposed changes:
- renaming the `MatchFoundController` to `PersonSearchController`
Locally with docker and unit test
this PR fixes jira ticket: **FAMS3-786**

change MatchFound Controller to PersonController

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

- Read status payload sent by the SearchApi webHooks
Locally with docker
this PR fixes jira ticket: **FAMS3-768**

Create a new endpoint to accept statuses from adapter

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/DynamicsAdapter.Web.Test.csproj
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
docker-compose.yml

this PR includes the following changes:
- Handling post to /PersonSearch/Accepted/{searchRequestId} for any accepted events
this PR fixes jira ticket: **pFAMS3-827**

As the dynamapter, I can handle PersonSearchAccepted events coming like /PersonSearch/Accepted/{searchRequestId}

---

README.md
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchCompleted.cs
app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchCompleted.cs
app/SearchApi/SearchApi.Web.Test/Search/PersonSearchCompletedConsumerTest.cs
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs
app/SearchApi/SearchApi.Web/Startup.cs

Add person search completed consumer
this PR fixes jira ticket: **821**

add person search completed consumer and unit test

---

openshift/templates/dynamics-adapter.dc.yaml

- update the internal route on openshift for dynadapter to searchapi

configured internal route for search-api

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchRejected.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchFailed.cs
app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchFailed.cs
app/SearchApi/SearchApi.Core/Adapters/Middleware/PersonSearchObserver.cs
app/SearchApi/SearchApi.Core/Adapters/Models/DefaultPersonSearchFailed.cs

Process Search Rejected
Unit test and tested with dynamics
this PR fixes jira ticket: **826**

 process search rejected

---

openshift/.pipeline/Jenkinsfile
openshift/templates/dynamics-adapter.bc.yaml
openshift/templates/sample-adapter.bc.yaml
openshift/templates/sample-adapter.dc.yaml
openshift/templates/search-api.bc.yaml

This change will build the 'Sample Adapter' contained in the FAMS3 repo and deploy it to the development environment.

Change to sample Adapter definition in public repo

---

app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs

This pr includes the following proposed change:
- Use MapDefaultControllerRoutes

replaced with mapDefaultController

---

app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core/Adapters/Middleware/PersonSearchObserver.cs
app/SearchApi/SearchApi.Core/OpenTracing/OpenTracingPublishFilter.cs
app/SearchApi/SearchApi.Core/OpenTracing/OpenTracingSendFilter.cs

- Add a branch to trigger exception in the sample app
- Fix issue with 
if the firstName of the request is `exception` then the sample adapter throws an exception
Local, Docker + Dynamics

Added support to send failure

---

app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs

- improving the message when the webhook fails.
Unit-Test only

Improved error message

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestAutoMapperProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/IdentificationType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/OptionSets/Models/Enumeration.cs

refactor IdentificationType, remove those searchApi value from IdentificationType. 
Doing the mapping in SearchRequestAutoMapperProfile.cs
tested locally
- [] I have commented my code, particularly in hard-to-understand areas
this PR fixes jira ticket: fams-870

refactor IdentificationType

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestAutoMapperProfile.cs

Change messages status
Unit testing.
this PR fixes jira ticket: **882**

updated search even status messages

---

openshift/templates/dynamics-adapter.bc.yaml
openshift/templates/search-api.bc.yaml

- Increase the memory of dynadapter && searchApi for openshift deployment
Manually on openshift by changing the pod configuration

Increased Memory limit

---

openshift/.pipeline/Jenkinsfile

Increase memory on Development environment .NET runtimes.
CICD

Increase runtime memory

---

openshift/.pipeline/Jenkinsfile
openshift/templates/rabbitmq.dc.yaml

This PR modifies the Jenkinsfile to also deploy out the project to the Test namespace.

CICD: Add .NET deployments to test

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Address.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchCompleted.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestAutoMapperProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/CanadianProvinceType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/LocationType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Country.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DynamicsEntity.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs

some class definition that related to Address for Dynamics
tested locally
this PR fixes jira ticket: FAMS-761(Create the structure for Address to be sent back to dynamics adapter)

some class definition that related to Address

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestAutoMapperProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Country.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

This pr is to upload address to dynamics. 
Will do Automapper unit tests in next pr.
Tested on local pc and unit tests.
this PR fixes jira ticket: FAMS-757

upload address to dynamics

---

README.md
app/SearchApi/SearchAdapter.Sample/Startup.cs
app/SearchApi/SearchApi.Core.Test/DependencyInjection/ServiceCollectionsExtensionsTest.cs
app/SearchApi/SearchApi.Core.Test/SearchApi.Core.Test.csproj
app/SearchApi/SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs

Implement sample adapter with search api core
Existing unit test for sample adapter works and running locally works also.
this PR fixes jira ticket: **put the jira ticket FAMS3-933 **

implement search core lib on sample adapter

---

openshift/.pipeline/Jenkinsfile

This PR is to deploy the ICBC Rest adapter to the Dev and Test environments.

Deploy ICBC adapter to Openshift

---

openshift/.pipeline/Jenkinsfile

This PR includes the following changes:
- fix path for the icbc rest adapter deployment
No-test

Fixed icbc path

---

app/SearchApi/SearchAdapter.Sample.Test/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePerson.cs
app/SearchApi/SearchApi.Core/Person/Contracts/Person.cs
app/SearchApi/SearchApi.Core/Person/Contracts/PersonalAddress.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

Read addresses from MatchFound payload and create address for each
tested locally
this PR fixes jira ticket: FAMS-758

Read addresses from MatchFound payload and create address for each

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TelephoneNumberType.cs
app/SearchApi/SearchAdapter.Sample.Test/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePerson.cs
app/SearchApi/SearchApi.Core/Person/Contracts/Person.cs
app/SearchApi/SearchApi.Core/Person/Contracts/PersonPhoneNumber.cs
app/SearchApi/SearchApi.Core/Person/Contracts/PersonalPhoneNumber.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

Add phone number to search
Generate class from open api spec
Refactored address to use generated class
Locally unit test.
Test with Dynamics
this PR fixes jira ticket: **FAMS3-942, FAMS3-943, FAMS-944**

Phone Number add to result

---

app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- Setting properties for the search api core package
- N/A

Added information about the core lib

---

app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Keys.cs

- A fix for the queue name for the adapters
Tested locally on docker

Fixed queue configuration for providers

---

app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/Address.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/PhoneNumber.cs
app/SearchApi/SearchAdapter.Sample.Test/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePerson.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

- Renaming Address and Phone Number Objects. 
Unit tests

Removed Personal from Address and PhoneNumbers

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/DynamicsHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/IdentificationType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonNameCategory.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TypeService.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Enums/PersonalIdentifierType.cs

include health check for optionset values for names
fix bug with identification type breaking health check
This change will require an update on search api core enumeration for identifier type.
Tested locally with unit test and via vpn directly with dynamics dev environment
this PR fixes jira ticket: **FAMS3-1064 & FAMS3-1065**

options set for name

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/Address.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/PersonalIdentifier.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/PhoneNumber.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj

- simplification of the address model

Simplified Address Model

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json

- Adding Serilog to `dynadapter`
Locally
this PR fixes jira ticket: **FAMS3-1060**

Adding Serilog to Dynadapter

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/ProviderProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Person/Contracts/PersonalIdentifier.cs

Attach supplied by to result in dynadapter
Unit testing
this PR fixes jira ticket: **FAMS3-1075**

attach supplied by to result

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Web/appsettings.json

refine address for dynamics
Tested locally
this PR fixes jira ticket: FAMS-1009

refine address for dynamics

---

openshift/.pipeline/Jenkinsfile
openshift/templates/dynamics-adapter.dc.yaml
openshift/templates/icbc-rest-adapter.dc.yaml
openshift/templates/icbc-web-adapter.bc.yaml
openshift/templates/icbc-web-adapter.dc.yaml

Hasn't been tested on openshift yet, will complete a test of the working branch on openshift dev before this is approved
this PR fixes jira ticket: **FAMS3-1100**

FAMS3-1100

---

openshift/.pipeline/Jenkinsfile

Removed sample adapter from promote to test stage

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Name.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/SearchAdapter.Sample.Test/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePerson.cs
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

Add name contract
tested locally
this PR fixes jira ticket: FAMS-1063

add name contract

---

test/load-test-plan.md

Updated the iterations from 120 to 3000. The total iterations will be shared by the number of virtual users. Removed duration because the test will be run for 3000 iterations irrespective of the duration set.
Documentation.

Update load test plan input

---

test/load-test-setup-and-run.md

Added k6 setup and run .md file
Documentation.

k6 load test setup and run .md file

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Name.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonNameCategory.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

Read name from MatchFound payload and create name for each
Tested locally
this PR fixes jira ticket: FAMS-1062(Read name from MatchFound payload and create name for each)

Read name from MatchFound payload

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

add new function to create name in dynamics for a given searchrequest
Tested locally
this PR fixes jira ticket: FAMS-1061,FAMS-989

add new function to create name in dynamics for a given searchrequest

---

test/load-test.json

This PR includes a psotman collection json file for search API.
Tested by running the script in postman

added load-test.json postman collection

---

openshift/templates/icbc-web-adapter.dc.yaml

fixed deployment config

---

openshift/templates/icbc-web-adapter.dc.yaml

add icbc_reset_url to dc yaml file
no testing. Need being reviewed carefully.
this PR fixes jira ticket: FAMS-1169

add icbc_reset_url to dc yaml file

---

openshift/.pipeline/Jenkinsfile
openshift/templates/cassandra.yaml
openshift/templates/configmap-cassandra.yaml
openshift/templates/jaeger-aio.dc.yaml
openshift/templates/jaeger.dc.yaml

Adding Jaeger All-In-One-Deployment to Dev and Test, plus template files

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/OptionSets/OptionSetService.cs

Filter health logs by setting up serilog filter.
This is part of the FAMS-1204. We only implement in dynAdapter. Once the result is good, we will do the same for other projects.
Tested locally
this PR fixes jira ticket: FAMS-1204

Filter health logs by setting up serilog filter

---

openshift/templates/dynamics-adapter.bc.yaml
openshift/templates/icbc-rest-adapter.bc.yaml
openshift/templates/rabbitmq.dc.yaml
openshift/templates/sample-adapter.bc.yaml
openshift/templates/search-api.bc.yaml

- Disabling Artifactory on non-essential builds while determining issues
- Attempting to softlink certificates as a way to deal with Corefx validation issues (SSL issues in builds)
- Small rabbitmq fix

Artifactory Troubleshooting

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/PersonalIdentifier.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

change SerialNumber to Value for PersonalIdentifier in SearchAPI and dynadapter
tested locally
this PR fixes jira ticket: FAMS-1253

change SerialNumber to Value for PersonalIdentifier in SearchAPI and dynadapter

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

update package version to 1.0.7
Tested locally

update package version 

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/Models/PersonRequest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DynamicsEntity.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs

dynadapter identifier mapping
Tested locally
this PR fixes jira ticket: FAMS-1257,1260,1261,1262,1270

dynadapter identifier mapping

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs

remove the fullText from ssg_address
this PR fixes jira ticket: FAMS-1293

remove the fullText from ssg_address

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

update the version

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

update contract version to 1.0.9
Tested locally

update contract version to 1.0.9

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

library version update

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs

Updated Person Model to include more fields
this PR fixes jira ticket: **FAMS3-1399**

person contract extended

---

app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

core library version updated

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

update person model to accept nullable boolean and version updated

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonNameCategory.cs

Map all fields in Name to ssg_alias correctly and upload to dynamics correctly.
Tested locally
this PR fixes jira ticket: FAMS-1397

upload name to dynamics 

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs

remove Employer from InformationSourceType as Dynamics remove it.
tested locally.

remove Employer as Dynamics remove it.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TelephoneNumberType.cs

Map and upload phone data to dynamics. Details here :
[FAMS3-1445] (https://justice.gov.bc.ca/jira/browse/FAMS3-1445)
[FAMS3-1446] (https://justice.gov.bc.ca/jira/browse/FAMS3-1446)
[FAMS3-1447] (https://justice.gov.bc.ca/jira/browse/FAMS3-1447)
Unit testing and locally tested with dev dynamics platform
this PR fixes jira ticket: **FAMS3-1447 & FAMS3-1446 & FAMS3-1445**

map phone to dynamics

---

app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

Add phone sample data to sample adapter
[1463] (https://justice.gov.bc.ca/jira/browse/FAMS3-1463)
Unit test
this PR fixes jira ticket: **FAMS3-1463**

add phone to sample adapter

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs

a bug fix for birthDatetime
tested locally

a bug fix for birthDatetime

---

app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json

Enable debugging logs for windows and system
tested locally

enable debugging logs for windows and system

---

openshift/templates/dynamics-adapter.dc.yaml
openshift/templates/icbc-rest-adapter.dc.yaml
openshift/templates/icbc-web-adapter.bc.yaml
openshift/templates/icbc-web-adapter.dc.yaml
openshift/templates/openssl.cm.yaml
openshift/templates/sample-adapter.dc.yaml
openshift/templates/search-api.dc.yaml
openshift/templates/sonarqube.yaml

- Changing to recreate rather than rolling to deal with data integrity issues
- Committing the openssl configmap that deals with ADFS handshake issues
- Changing build to not use default socket library in attempt to fix Artifactory issues.

Stability issues and fixes

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/RelatedPerson.cs
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

Add relatedPerson for searchApi contract.
Tested locally
this PR fixes jira ticket: FAMS3-1484

Feature/contract/related person for searchApi

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

Add Employment for searchApi contract.
[FAMS3-1483] (https://justice.gov.bc.ca/jira/browse/FAMS3-1483)
Unit test
this PR fixes jira ticket: **FAMS3-1483**

add employment contract and unit test

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

Update package version and changed the repo to point to nexus
[FAMS3-1548] (https://justice.gov.bc.ca/jira/browse/FAMS3-1548)
Unit test
this PR fixes jira ticket: **FAMS3-1548**

update package version

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs

Update employment contract
[FAMS3-1558] (https://justice.gov.bc.ca/jira/browse/FAMS3-1558)
- refactored employer to use phone contract (Locate services is expecting multiple)
- add website property
Unit test
this PR fixes jira ticket: **FAMS3-1558**

update employment contract to add website and use phone entity

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

update lib version

---

app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

Update sample fakes for sample adapter
[FAMS3-1562] (https://justice.gov.bc.ca/jira/browse/FAMS3-1562)
Unit test
this PR fixes jira ticket: **FAMS3-1562**

search adapter fakes

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

Update employment entity and fakes
[FAMS3-1561] (https://justice.gov.bc.ca/jira/browse/FAMS3-1561)
[FAMS3-1562] (https://justice.gov.bc.ca/jira/browse/FAMS3-1562)
new library will be pushed to nexus and artefactory
Unit test

update library and contract and fakes

---

app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

add related person to sample
Tested locally
- [] I have commented my code, particularly in hard-to-understand areas
this PR fixes jira ticket:FAMS3-1583

add related person to sample

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/RelatedPerson/SSG_RelatedPerson.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/GenderType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonRelationType.cs

map related person from search Api to dynadatper
Tested locally
this PR fixes jira ticket: FAMS3-1584

map related person in dynadapter

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Save employment records in dynamics, link phones and update name message
https://justice.gov.bc.ca/jira/browse/FAMS3-1564
https://justice.gov.bc.ca/jira/browse/FAMS3-1565
https://justice.gov.bc.ca/jira/browse/FAMS3-1587
Unit test and locally with dev dynamics via VPN
this PR fixes jira ticket: **FAMS3-1587 & FAMS3-1564  & FAMS3-1565**

save employment records in dynamics and link phones

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/DynamicsHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/GenderType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TypeService.cs

Add health check for related person
Tested locally
this PR fixes jira ticket: FAMS3-1596

health check for related person

---

app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs

Update unit test for employment
Unit test

unit test employment

---

README.md
docker-compose.yml

add redis to docker (local dev)
[FAMS3-1631] (https://justice.gov.bc.ca/jira/browse/FAMS3-1631)
Locally tested (docker-compose up)
this PR fixes jira ticket: **FAMS3-1631**

set up docker compose for redis and redis commander

---

app/SearchApi/BcGov.Fams3.Redis.Test/BcGov.Fams3.Redis.Test.csproj
app/SearchApi/BcGov.Fams3.Redis.Test/UnitTest1.cs
app/SearchApi/BcGov.Fams3.Redis/BcGov.Fams3.Redis.csproj
app/SearchApi/BcGov.Fams3.Redis/Configuration/RedisConfiguration.cs
app/SearchApi/BcGov.Fams3.Redis/DependencyInjection/IServiceCollection.cs
app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs
app/SearchApi/SearchApi.sln
docker-compose.yml

https://justice.gov.bc.ca/jira/browse/FAMS3-1632
this PR fixes jira ticket: **FAMS3-1632**

set up redis library

---

app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs
app/SearchApi/BcGov.Fams3.Redis/Model/SearchRequest.cs

https://justice.gov.bc.ca/jira/browse/FAMS3-1632
this PR fixes jira ticket: **FAMS3-1632**

ad model and update service

---

.github/workflows/sonarscan.yml

To differentiate the sonar job from dotnet job

change label on sonar build

---

app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

update json swagger for searchApiRequest dataProvider
Tested locally.
this PR fixes jira ticket: FAMS-1472-Part1

update json swagger for searchApiRequest dataProvider

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

https://justice.gov.bc.ca/jira/browse/FAMS3-1753
Unit test
this PR fixes jira ticket: **FAMS3-1753**

Sample Adapter Update

---

openshift/.pipeline/Jenkinsfile
openshift/templates/bchydro-rest-adapter.dc.yaml
openshift/templates/bchydro-web-adapter.bc.yaml
openshift/templates/datapartner-rest-adapter.bc.yaml
openshift/templates/datapartner-web-adapter.bc.yaml
openshift/templates/datapartner-web-adapter.dc.yaml
openshift/templates/icbc-rest-adapter.dc.yaml

https://justice.gov.bc.ca/jira/browse/FAMS3-1764
this PR fixes jira ticket: **FAMS3-1764**

Multi Service Deployment

---

.github/pull_request_template.md
.github/workflows/sonarscan.yml
app/SearchApi/SearchApi.Web.Test/Messaging/DispatcherTest.cs
app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs
app/SearchApi/SearchApi.Web/Startup.cs
docker-compose.yml

- a new dispatcher that routes request to specific queues
Running locally + unit tests

Add new dispatcher

---

docker-compose.yml

This includes a change on the network for docker

setting up bridge network

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/PersonalIdentifierType.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

add otherDriverLicense and bcDriverlicesnse to contract.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/IdentificationType.cs

dynadapter-mapping bcdl and oopdl

---

.github/workflows/dotnetcore.yml
app/DynamicsAdapter/DynamicsAdapter.Web.Test/DynamicsAdapter.Web.Test.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Fams3Adapter.Dynamics.Test.csproj
app/DynamicsAdapter/Fams3Adapter.Dynamics/Fams3Adapter.Dynamics.csproj
app/SearchApi/BcGov.Fams3.Redis.Test/BcGov.Fams3.Redis.Test.csproj
app/SearchApi/BcGov.Fams3.Redis/BcGov.Fams3.Redis.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample.Test/SearchAdapter.Sample.Test.csproj
app/SearchApi/SearchAdapter.Sample/SearchAdapter.Sample.csproj
app/SearchApi/SearchApi.Core.Test/SearchApi.Core.Test.csproj
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs
app/SearchApi/SearchApi.Web.Test/SearchApi.Web.Test.csproj
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj

- update to dotnet core 3.1
Running the app locally

updated to 3.1

---

app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
app/SearchApi/SearchApi.Web/Startup.cs

- Temporary removed redis to get the application running, also IDistributedCache is already implemented for redis.

Temporary remove redis

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/nswag.json

- fix swagger dotnet core version

 fix nswag version

---

app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs

- Always Capitalize the queue name

Capitalize queue name always

---

app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs

remove the space from "BC Hydro"
this is temporary solution.
Tested locally

remove space

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchCompleted.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchFailed.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchCompleted.cs

contract update: complete event accept multi persons for each request.

---

app/SearchApi/BcGov.Fams3.Redis/Configuration/RedisConfiguration.cs
app/SearchApi/BcGov.Fams3.Redis/DependencyInjection/IServiceCollectionExtensions.cs
app/SearchApi/SearchApi.Web/appsettings.json
docker-compose.yml

- https://justice.gov.bc.ca/jira/browse/FAMS3-1852
Quick change to use password for redis

use password for redis

---

openshift/templates/mhsd-rest-adapter.dc.yaml
openshift/templates/mhsd-web-adapter.bc.yaml

- Update config Social development deployment

add configuration for social development

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/Models/ProviderProfileExtensionTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/ProviderProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-1877
Unit test

update mhsd as supplied by

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs

-fix employment upload issue from msdpr
Tested locally with dev dynamics.

fix employment upload issue from msdpr

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/Models/ProviderProfileExtensionTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/ProviderProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-1891

Remove Mapping for MHSD [DynAdapter]

---

openshift/templates/sonarqube-postgresql-template.yaml

* renamed sonarqube.yaml
* updated template

Added sonarqube-postgresql-template.yaml

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

pull fileID from dynamics

---

openshift/templates/config/dynadapter-config.yaml
openshift/templates/config/redis-connection.yaml

Devops secrets

---

openshift/docker-images/sonarqube-dotnet/Dockerfile
openshift/templates/jenkins-slave-sonarqube-dotnet.yaml

Adding jenkins slave sonarqube template and docker file

Devops sonarscan

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-1922
Ran local test using the browser to check the spec and also ensured the job is still running

add open api to dynadapter

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/appsettings.json

- FAMS-1940(add fileID to log in Request Sending work flow.)
Tested locally

add fileID to log in Request Sending work flow.

---

openshift/templates/pipelines/bchydro-rest-adapter-pipeline.yaml
openshift/templates/pipelines/bchydro-web-adapter-pipeline.yaml
openshift/templates/pipelines/dynadapter-pipeline.yaml
openshift/templates/pipelines/icbc-rest-adapter-pipeline.yaml
openshift/templates/pipelines/icbc-web-adapter-pipeline.yaml
openshift/templates/pipelines/mhsd-rest-adapter-pipeline.yaml
openshift/templates/pipelines/mhsd-web-adapter-pipeline.yaml
openshift/templates/pipelines/search-api-pipeline.yaml

Added pipelines for:
1. search-api
2. dyadapter
3. bchydro rest/web adapters
4. icbc rest/web adapters
5. mhsd rest/web adapters

Add pipelines

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/BankInfo.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

-FAMS3-1985: searchApi defines BankInformation contract
Tested locally

searchApi - bankInfo contract

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchEvent.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchOrdered.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Middleware/PersonSearchObserver.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Models/DefaultPersonSearchAccepted.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Models/DefaultPersonSearchFailed.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchAccepted.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchAdapeterEvent.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchCompleted.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchFailed.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchRejected.cs

- FAMS-1941(add FileID to log in Response Returning working flow.)
Tested locally

add fileId to all event.

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs

-FAMS-1941: add FileID to log in Response Returning working flow.
Tested locally

add FileId to log

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchFinalized.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchFinalized.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchFinalized.cs
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs
app/SearchApi/SearchApi.Web/Notifications/PersonSearchFinalizedCls.cs
app/SearchApi/SearchApi.Web/Notifications/PersonSearchFinalizedEvent.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs

- FAMS-1941(add FileID to log in Response Returning working flow.)
Tested locally
- [] I have made corresponding changes to the documentation

finalizedEvent and FileId in response events

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/AssetOwner.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Vehicle.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

- FAMS-2016(searchApi defines Compensation contract)
Tested locally

Feature/search api/vehicle contract definition

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Address.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/AssetOwner.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/BankInfo.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Name.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/OtherAsset.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/PersonalIdentifier.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/PersonalInfo.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Phone.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/ReferenceDate.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Vehicle.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchFinalized.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/ProviderProfile.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Configuration/ProviderProfileOptions.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

-FAMS3-2035(searchApi defines OtherAsset contract)
Tested locally

otherasset contract and clean up unused using

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/AssetOwner/SSG_AssetOwner.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/BankInfo/SSG_Asset_BankingInformation.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/OtherAsset/SSG_Asset_Other.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchAdapter.Sample/appsettings.json

- FAMS3-2036(dynAdapter can map OtherAsset to dynamics)
Tested locally

dynadapter uploads other asset to dynamics

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/CompensationClaim.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs

- FAMS3-2016(searchApi defines Compensation contract)
Tested locally

compensation claim contract

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/SearchApi/SearchApi.Web/Program.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
app/SearchApi/SearchApi.Web/appsettings.json
openshift/templates/config/splunk-config.yaml

Devops splunk

---

openshift/templates/applications/deployments/rest-adapter.yaml
openshift/templates/applications/deployments/web-adapter.yaml

Adding data partner env variable for splunk

Adding data partner env variable for splunk

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

package version updated

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/BankInfo/SSG_Asset_BankingInformation.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/CompensationClaim/SSG_Asset_WorkSafeBcClaim.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

- FAMS3-2017(dynAdapter can map CompensationClaim to dynamics)
Tested locally

Create CompensationClaim in Dynamics

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json

- FAMS3-2086(refactor dynAdaptor and searchApi web adapter for changing AssetOwner to InvolvedParty.)-dynadapter part
Tested locally

change assetOwner to InvolvedParty-dyadapter

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/DynamicsAdapter.Web.Test.csproj
app/DynamicsAdapter/DynamicsAdapter.Web.Test/MockLoggerExtensions.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json

FAMS3-2156(Refactor/file id format, add data partner, searchRequestJob unit tests)
- [] New feature (non-breaking change which adds functionality)
Tested locally

Refactor/file id format, add data partner, searchRequestJob unit tests

---

app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/Program.cs
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs
app/SearchApi/SearchApi.Web/appsettings.json

-update FileId format in searchApi
Tested locally

update FileId format in searchApi

---

splunk/dashboards/fams3_executive_summary.xml
splunk/dashboards/fams3_ops_dashboard.xml

adding splunk dashboards

---

.github/labeler.yml

add label to splunk

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonFound.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonFoundResult.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchCompleted.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs

- FAMS3-2199(dyandapter-filter out unique id from searchApi request.)
Tested locally

filter out the unique identiferes

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/CompensationClaim/SSG_Asset_WorkSafeBcClaim.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/RelatedPerson/SSG_RelatedPerson.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

-FAMS3-2056((Cascading Incorrect Status) Create middle entity record with Identifier - result linkage)-Step1 -make entities returned id
Tested locally

Feature/upload transaction-make all related entity returns ID

---

openshift/README.md
openshift/docker-images/selenium-maven/Dockerfile
openshift/templates/builds/pipelines/web-rest-adapters-scans.yaml
openshift/templates/config/selenium-maven-config.yaml
openshift/templates/jenkins-slave-selenium-maven.yaml

Adding Selenium/Cucumber BDT, updating pipelines and readme

Devops selenium

---

openshift/README.md
splunk/dashboards/fams3_ops_dashboard.xml

Spelling fixes in 
* dashboard
* documentation

fixing spellings in dashboard and documentation

---

openshift/templates/applications/deployments/rest-inbound-adapter.yaml
openshift/templates/applications/routes/rest-inbound-adapter.yaml
openshift/templates/applications/services/rest-inbound-adapter.yaml
openshift/templates/builds/builds/rest-inbound-adapter.yaml
openshift/templates/builds/images/rest-inbound-adapter.yaml
openshift/templates/builds/pipelines/rest-inbound-adapter.yaml
openshift/templates/config/rest-inbound-config.yaml
openshift/templates/wsbc-rest-adapter.dc.yaml
openshift/templates/wsbc-rest-inbound-adapter.dc.yaml
openshift/templates/wsbc-web-adapter.bc.yaml

add configs and build pipeline

deploy worksafebc

---

openshift/templates/applications/services/dynadapter.yaml
openshift/templates/applications/services/search-api.yaml
openshift/templates/builds/pipelines/dynadapter.yaml
openshift/templates/builds/pipelines/rest-adapter.yaml
openshift/templates/builds/pipelines/rest-inbound-adapter.yaml
openshift/templates/builds/pipelines/search-api.yaml
openshift/templates/builds/pipelines/web-adapter.yaml

* Fixing variable names
* Service templates
* Deployment pipeline

fixing openshift pipeline bugs

---

openshift/README.md
openshift/templates/builds/pipelines/rest-inbound-adapter.yaml

inbound deployment config

---

openshift/README.md
openshift/templates/config/rest-inbound-config.yaml

- quick fix for config for inbound

fix broken name

---

openshift/README.md
openshift/templates/builds/pipelines/dynadapter-scans.yaml
openshift/templates/builds/pipelines/search-api-scans.yaml
openshift/templates/builds/pipelines/web-rest-adapters-scans.yaml
openshift/templates/static-web-server.dc.yaml

* Adding template for reporting static web server
* Updating pipeline
* Updating readme

Adding reporting server

---

openshift/README.md

Adding follow link to curl in README

Adding follow link to curl in README

---

openshift/README.md
openshift/templates/builds/builds/fmep-inbound-adapter.yaml

- https://justice.gov.bc.ca/jira/browse/FAMS3-2287

update pipeline for mock fmep

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchReceived.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample.Test/SearchResultConsumerTest.cs

-FAMS3-2263(testing and verify full cycle worksafe bc working)
Local testing

Search api/contract/received/string change recevied event payload type to be string

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs

-bug fixing: if sourceIdentifier is null, should return null.
Tested locally and new unit tests

if sourceIdentifier is null, return null.

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/IdentificationType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs

-FAMS3-2263(openshift testing)
Tested locally

add informationSource workSafeBC and update Identificationtype for dynamics

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/ApiGateway/ApiGatewayHandler.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Auth/OAuthApiException.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/RegisterFailedException.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_CountrySubdivision.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Guard.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Keys.cs

- Clear Sonar qube code smells - part 1

Sonar/dynadaptor code smell clearup - part1

---

app/DynamicsAdapter/DynamicsAdapter.Web/ApiGateway/ApiGatewayHandler.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs

Auto stash before rebase of "origin/master"

---

app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Config/DuplicateDetectionConfigServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Config/DuplicateDetectionConfigService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Config/DuplicateRuleConfigService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Config/SSG_DuplicateDetectionConfig.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

-FAMS3-2310(read ssg_duplicatedetectionconfig entity as the settings.)

reading duplicate config from dynamics

---

app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs

Description
- https://justice.gov.bc.ca/jira/browse/FAMS3-2094
Type of change
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Refactoring / Documentation
if your change is a breaking change, please add breaking change label to this PR
How Has This Been Tested?
Checklist:
My code follows the style guidelines of this project
I have performed a self-review of my own code
I have made corresponding changes to the documentation
New and existing unit tests pass locally with my changes

add cache ignore

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchSubmitted.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- https://justice.gov.bc.ca/jira/browse/FAMS3-2325
Unit Test

new contract

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchSubmitted.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

- FAMS3-2328(dynadapter - create Submitted Event then the search request is submitted to data provider.)
Tested locally and add new unit tests

dynadapter Upload submitted event

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs

…rchAdapterEvent
- bug fixing
Tested locally

updated to new version to make submitted event inherit from PersonSearchAdapterEvent

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Config/DuplicateDetectionServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Config/DuplicateDetectionService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DynamicsEntity.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Person/SSG_Person.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/ResultTransaction/SSG_SearchRequestResultTransaction.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

-FAMS3-2336(Address Entity - searchApi -duplicated)

Duplicate/ detect address duplication

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/DynamicsHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/IncomeAssistanceStatusType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TypeService.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2272
Unit test

add income assistance options

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Config/DuplicateDetectionServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Config/DuplicateDetectionService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

-FAMS3-2339(Identifier Entity -Search Api - duplicates)
Tested locally and new unit tests

Add Duplicate for identifier

---

openshift/templates/builds/pipelines/dynadapter-scans.yaml
openshift/templates/builds/pipelines/search-api-scans.yaml
openshift/templates/builds/pipelines/web-rest-adapters-scans.yaml

Signed-off-by: Ebenezer Muthiah <ebe1234@gmail.com>
Add nuget config for dotnet restore

Add nuget config for dotnet restore

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs

-fix "when name entity type is null, mapping throw null exception."
Tested locally

bug-name type null, when name entity type is null, mapping throw null exception.

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Duplicate/DuplicateDetectionService.cs

- bug fix: different case data, should considered as same.
Tested locally

duplicate string changed to all lower case for comparing.

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/SearchRequest/SearchRequestNotification.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/SearchAdapter.Sample/Startup.cs
app/SearchApi/SearchApi.Core.Test/DependencyInjection/ServiceCollectionsExtensionsTest.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2387

contract updated with extension

---

app/SearchApi/AgencyAdapter.Sample/SearchRequest/SearchRequestEventSample.cs
app/SearchApi/AgencyAdapter.Sample/SearchRequest/SearchRequestResponseConsumer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Agency.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/SearchRequest/SearchRequestEvent.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Middleware/SearchRequestObserver.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Models/DefaultSearchRequestFailed.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- https://justice.gov.bc.ca/jira/browse/FAMS3-2424
Contract change with no testing.

add contract

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs
app/SearchApi/SearchRequest.Adaptor.Test/Consumer/SearchRequestOrderedConsumerTest.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Consumer/SearchRequestOrderedConsumer.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs
app/SearchApi/SearchRequest.Adaptor/appsettings.json

- FAMS3-2492(FMEP Integration Verification - make sure submitted sample FMEP request can go through the 3 micro-services and uploaded to dyanmics correctly.)
Tested locally

bug fixing : agent email, url and cleanup

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_EmploymentContact.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/InsuranceClaim/SSG_Asset_ICBCClaim.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/InsuranceClaim/SSG_SimplePhoneNumber.cs

- FAMS3-Dynadapter - upload phone number to two fields of its entity and update duplicate detection config.

deal with duplicate phone number issue (phone number got formatted after upload)

---

docker-compose.yml
openshift/README.md
openshift/templates/applications/deployments/request-api.yaml
openshift/templates/applications/routes/request-api.yaml
openshift/templates/applications/services/request-api.yaml
openshift/templates/builds/builds/fams-request-inbound-adapter.yaml
openshift/templates/builds/builds/request-api.yaml
openshift/templates/builds/pipelines/request-api.yaml
openshift/templates/config/requestapi-webhook-config.yaml

- https://justice.gov.bc.ca/jira/browse/FAMS3-2521
DevOps

add deployment config

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs

-So basically as long as it has not been closed or already cancelled, the SR can be cancelled. If no error thrown, then it is successful.

Bug/cancel sr: 

---

openshift/templates/config/agency-outbound-api-webhook-config.yaml

- https://justice.gov.bc.ca/jira/browse/FAMS3-2522

FMEP OpenShift

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_Notes_Test.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Notes/SSG_Notes.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

- FAMS3-2466([DyanAdapter] Perform update)  - Notes part

update sr - notes

---

app/SearchApi/SearchRequest.Adaptor/Publisher/SearchRequestEventPublisher.cs

- bug fix: wrong queue name
Tested locally

fix wrong queue name

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DataProvider/SSG_DataProvider.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2560
Unit test and local testing against dynamics dev

get list of failed searches with unit test and local testing

---

app/SearchApi/BcGov.Fams3.Utils/BcGov.Fams3.Utils.csproj
app/SearchApi/BcGov.Fams3.Utils/Logger/AgencyCodeEnricher.cs
app/SearchApi/BcGov.Fams3.Utils/Logger/DataPartnerEnricher.cs
app/SearchApi/BcGov.Fams3.Utils/Logger/RequestRefEnricher.cs
app/SearchApi/BcGov.Fams3.Utils/Logger/SearchRequestKeyEnricher.cs
app/SearchApi/BcGov.Fams3.Utils/Object/IUpdatableObjectExtensions.cs
app/SearchApi/BcGov.Fams3.Utils/String/StringExtension.cs

- FAMS3-2603(Process FMEP Request with XML as the input request.)

add isValidXml and fix compiling issue

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/IdentificationType.cs
docker-compose.yml

fix running docker compose locally.

fix error with running local docker compose

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs

- fixing bug in updating identifier and person

fix the bug in updating identifier and person

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs

- change to remove the requestID from URL signature.
Tested locally

make cancel working

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Contructors.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2133

2133 issues improvement - https://justice.gov.bc.ca/jira/browse/FAMS3-2133

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

-FAMS-2657(fix 4 null reference bugs reported in sonar cube for Dynadapter.)

fix sonar bugs and update unit tests.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonRelationType.cs

- fams3-2674(dynadaptor-related person, mapping LALW to May Live With" (867670008))
Unit tests

mapping lalw

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs

-FAMS3-2676(rejected event for update, cancel and new)

Fix/check sr status before update.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Person/SSG_Person.cs

- Person Gender mapping to optionset. Update sr for identifier, change to add new identifier.

FAMS3-2679

---

app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs
app/SearchApi/SearchApi.Web.Test/Configuration/DeepSearchOptionsTest.cs
app/SearchApi/SearchApi.Web.Test/DeepSearch/IDeepSearchServiceTest.cs
app/SearchApi/SearchApi.Web.Test/DeepSearch/RegistryTest.cs
app/SearchApi/SearchApi.Web.Test/DeepSearch/Schema/WaveMetaDataTest.cs
app/SearchApi/SearchApi.Web.Test/KeysTest.cs
app/SearchApi/SearchApi.Web.Test/Messaging/DispatcherTest.cs
app/SearchApi/SearchApi.Web/Configuration/DeepSearchOptions.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/DeepSearch/Registry.cs
app/SearchApi/SearchApi.Web/DeepSearch/Schema/WaveMetaData.cs
app/SearchApi/SearchApi.Web/Keys.cs
app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchApi.Web/appsettings.json

- https://justice.gov.bc.ca/jira/browse/FAMS3-2661
- https://justice.gov.bc.ca/jira/browse/FAMS3-2662
Unit Tested

Deep Search Config

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_SearchRequest_Test.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Keys.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

- FAMS3-2695(add xml body back to cancel search request.)

unit tests update and cancel reason

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchApi.Web/appsettings.json

- Feature/2690(add applicant person to PersonSearchRequest)
- Some SearchApi small issues

Feature/2690(add applicant person to PersonSearchRequest)

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/StartupTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyResponseController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyResponseService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Models/SearchResponseReady.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SSG_SearchRequestResponse.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SearchResponseService.cs

FAMS3-2711([dynadaptor]provide endpoint for Dynamics to notify SR is closed.)
Tested locally

Feature/response/endpoint : for dynamics to return closed SR.

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Configuration/RetryConfiguration.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Keys.cs
app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchAdapter.Sample/Startup.cs
app/SearchApi/SearchAdapter.Sample/appsettings.json
app/SearchApi/SearchApi.Core.Test/Configuration/RetryConfigurationTest.cs
app/SearchApi/SearchApi.Core.Test/DependencyInjection/ServiceCollectionsExtensionsTest.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2779
Unit test and local testing

fix retry and throttle in request api and contract with sample adapter

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/DynamicsHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchCompleted.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/DataPartners/DataPartnerServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DataProvider/SSG_DataProvider.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/SearchSpeedType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TypeService.cs
app/SearchApi/AgencyAdapter.Sample/SearchRequest/SearchRequestEventSample.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/SearchSpeedType.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/ProviderProfile.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Configuration/ProviderProfileOptions.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchApi.Core.Test/Fake/FakeProviderProfile.cs
app/SearchApi/SearchApi.Web.Test/DeepSearch/IDeepSearchServiceTest.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs
app/SearchApi/SearchApi.Web/Notifications/PersonSearchFinalizedEvent.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

- Update dynamics with message in completed and add fast and slow auto search

refactor and update wave search in dynamics

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/SearchApi/BcGov.Fams3.Redis/Model/SearchRequest.cs
app/SearchApi/SearchApi.Web.Test/Messaging/DispatcherTest.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchDispatcher.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/DeepSearch/Schema/WaveSearchData .cs
app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs

- fix bug that is excluding data partner with null new parameter in new wave.

check null and update wave

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Person/SSG_Person.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/RelatedPerson/SSG_RelatedPerson.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs

-FAMS3-2843(dyanadapter-add DisplayName to each entity property.)
no testing

add displayName

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchRequest_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Exceptions/AgencyRequestException.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Agency.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Name.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/RelatedPerson.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs

Feature/search api/request contract, notification, rejected

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs

-Add could not locate to the employment and address

add could not locate for address and employment

---

openshift/templates/applications/deployments/file-adapter.yaml
openshift/templates/applications/routes/file-adapter.yaml
openshift/templates/applications/services/file-adapter.yaml
openshift/templates/builds/builds/file-adapter.yaml
openshift/templates/builds/images/file-adapter.yaml
openshift/templates/builds/pipelines/file-adapter.yaml
openshift/templates/config/file-adapter-config.yaml

- https://justice.gov.bc.ca/jira/browse/FAMS3-2870

JCA deployment

---

openshift/templates/applications/routes/dynadapter.yaml
openshift/templates/applications/routes/request-api.yaml
openshift/templates/applications/routes/rest-adapter.yaml
openshift/templates/applications/routes/rest-inbound-adapter.yaml
openshift/templates/applications/routes/search-api.yaml
openshift/templates/builds/pipelines/dynadapter.yaml
openshift/templates/builds/pipelines/file-adapter.yaml
openshift/templates/builds/pipelines/rest-adapter.yaml
openshift/templates/builds/pipelines/rest-inbound-adapter.yaml
openshift/templates/builds/pipelines/web-adapter.yaml

change endpoints to private

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs

-FAMS-2876
Tested locally and unit tests.

read if it is a prescreen sr

---

app/SearchApi/BcGov.Fams3.Redis/Model/SearchRequest.cs
app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs

the last part of preScreening
Tested locally

add for prescreen sr (not use deep search)

---

openshift/templates/applications/deployments/file-adapter.yaml
openshift/templates/config/fams3-jca-private-key.yaml

update config for certs

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/JCAPerson.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchRequest.Adaptor/Program.cs

- FAMS3-2878
Tested locally with unit tests

Feature/contract JCA info

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs

fix daysOpen bug

---

openshift/templates/applications/deployments/file-adapter.yaml

config change

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-2920

refactor completed event to display source id

---

app/SearchApi/BcGov.Fams3.Redis.Test/CacheServiceTest.cs
app/SearchApi/BcGov.Fams3.Redis/BcGov.Fams3.Redis.csproj
app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs

update redis lib

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs

update cache delete JCA

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

fix the closed ia mapping issue

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

finalize update

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs

- fix: the exception is thrown when search request is finalized.
Tested locally

fix bug-not finalized

---

app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
docker-compose.yml

- https://justice.gov.bc.ca/jira/browse/FAMS3-2960
- https://justice.gov.bc.ca/jira/browse/FAMS3-2961
- Finalize S - API - Request only when all DP is completed including JCA
Local testing with dynamics dev instance

testing and fixes

---

app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchDispatcher.cs
app/SearchApi/SearchApi.Web/DeepSearch/IDeepSearchService.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
app/SearchApi/SearchApi.Web/People/PeopleController.cs
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs

- FAMS3-Duplicates and Deep search
Tested locally

add log and do a fix.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/SearchApi/BcGov.Fams3.Redis.Test/CacheServiceTest.cs

- quick fix to check if SR is already polled even it not marked in progress to prevent duplicate initiation
Local testing with dynamics via vpn

add SR check on poll

---

app/SearchApi/SearchApi.Web.Test/DeepSearch/IDeepSearchServiceTest.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs

-Deep Search-Rejected event, wave need to be able to finalized.
Tested locally and unit tests.

fix bug-rejected, search cannot be finalized.

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Configuration/RetryConfiguration.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/SearchApi.Core.Test/Configuration/RetryConfigurationTest.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- fix the retry config typo
Tested locally

fix retry config typo

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Keys.cs
app/SearchApi/SearchApi.Web/SearchApi.Web.csproj

fix retry policy

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/IA/IASearchEvent.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/IA/IASearchFailed.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/IA/IASearchOrdered.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/IA/IASearchResult.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Middleware/IASearchObserver.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Middleware/SearchRequestObserver.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Models/DefaultIASearchFailed.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Configuration/ThrottleConfiguration.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Keys.cs
app/SearchApi/SearchAdapter.Sample.Test/IAConsumerTest.cs
app/SearchApi/SearchAdapter.Sample/IA/IASearchConsumer.cs
app/SearchApi/SearchAdapter.Sample/IA/IASearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/Startup.cs
app/SearchApi/SearchAdapter.Sample/appsettings.json
app/SearchApi/SearchApi.Core.Test/Configuration/ThrottleConfigurationTest.cs
app/SearchApi/SearchApi.Core.Test/DependencyInjection/ServiceCollectionsExtensionsTest.cs
app/SearchApi/SearchApi.Web/appsettings.json

- https://justice.gov.bc.ca/jira/browse/FAMS3-3027

ia consumer

---

app/SearchApi/BcGov.ApiKey.Middleware.Test/ApiKeyMiddlewareTest.cs
app/SearchApi/BcGov.ApiKey.Middleware.Test/BcGov.ApiKey.Middleware.Test.csproj
app/SearchApi/BcGov.ApiKey.Middleware/ApiKeyMiddleware.cs
app/SearchApi/BcGov.ApiKey.Middleware/BcGov.ApiKey.Middleware.csproj
app/SearchApi/SearchApi.sln
app/SearchApi/SearchRequest.Adaptor/SearchRequest.Adaptor.csproj
app/SearchApi/SearchRequest.Adaptor/Startup.cs
app/SearchApi/SearchRequest.Adaptor/appsettings.json

add api key lib and add to RequestApi

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/SearchApi/BcGov.ApiKey.Middleware.Test/ApiKeyMiddlewareTest.cs
app/SearchApi/BcGov.ApiKey.Middleware/ApiKeyMiddleware.cs
app/SearchApi/BcGov.ApiKey.Middleware/BcGov.ApiKey.Middleware.csproj
app/SearchApi/BcGov.ApiKey.Middleware/SwaggerApiKeyHeader.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

add apikey field for swagger and use apiKey in Dynadaptor

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/IA/IASearchEvent.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/Adapters/Models/DefaultIASearchFailed.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BatchFactory/ConsumerBatchFactory.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs
app/SearchApi/SearchAdapter.Sample.Test/IAConsumerTest.cs
app/SearchApi/SearchAdapter.Sample.Test/PersonSearchValidatorTest.cs
app/SearchApi/SearchAdapter.Sample/IA/IASearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/Startup.cs
app/SearchApi/SearchApi.Core.Test/DependencyInjection/ServiceCollectionsExtensionsTest.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-3040
- https://justice.gov.bc.ca/jira/browse/FAMS3-3027
- https://justice.gov.bc.ca/jira/browse/FAMS3-3038
- https://justice.gov.bc.ca/jira/browse/FAMS3-3038
- https://justice.gov.bc.ca/jira/browse/FAMS3-3039
Unit Test

add contract and update sample

---

app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchResponse/SearchResponseServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_CountrySubdivision.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SearchResponseService.cs

-FMEP require response address : province should be two letter code. We changed that.
Tested locally

add for provinceCode

---

README.md

https://github.com/bcgov/fams3/issues/452

repo-mountie update

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

- fix the weird bug about unit test-related person.
Tested locally

fix the weird bug about unit test-related person.

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/InsuranceClaim/SSG_Asset_ICBCClaim.cs

-change to use ssg_claimtypetext

change to use ssg_claimtypetext

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SearchResponseService.cs
openshift/templates/applications/deployments/ia-search-web-adapter.yaml
openshift/templates/applications/routes/ia-search-web-adapter.yaml
openshift/templates/applications/services/ia-search-web-adapter.yaml
openshift/templates/builds/builds/ia-search-web-adapter.yaml
openshift/templates/builds/pipelines/ia-search-web-adapter.yaml
openshift/templates/config/ia-search-config.yaml
openshift/templates/config/ia-sftp-config.yaml
openshift/templates/config/ia-throttle-config.yaml

- Deployment config for IA Search

deployment config

---

openshift/README.md
openshift/templates/builds/builds/ia-search-web-adapter.yaml
openshift/templates/builds/pipelines/ia-search-web-adapter.yaml

update config and add readme

---

openshift/templates/applications/deployments/ia-search-web-adapter.yaml

update deploy config

---

openshift/templates/applications/deployments/ia-search-web-adapter.yaml

config update

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchResponse/SearchResponseServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Email/SSG_Email.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/InsuranceClaim/SSG_Asset_ICBCClaim.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SSG_SearchRequestResponse.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SearchResponseService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SocialMedia/SSG_Electronica.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/EmailType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/SocialMediaType.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Address.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Email.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employer.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/InsuranceClaim.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/SocialMedia.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- https://justice.gov.bc.ca/jira/browse/FAMS3-3124?

Fix/fams3 contract and mapping 

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/LocationType.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Address.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- https://github.com/bcgov-c/fams3-openshift/pull/251 -  add name for address
Tested locally

 add name to address

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchResponse/SearchResponseService.cs

-add RequestPriority, Birthdate, gender and searchReasonCode to SR.

add additional data for SR.

---

app/SearchApi/BcGov.Fams3.Utils.Test/StringExtensionTest.cs
app/SearchApi/BcGov.Fams3.Utils/BcGov.Fams3.Utils.csproj
app/SearchApi/BcGov.Fams3.Utils/String/StringExtension.cs

add toTitleCase to string

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

- mapping for dod confirmed is missing

fix "mapping for dod confirmed is missing"

---

app/SearchApi/BcGov.Fams3.Utils.Test/StringExtensionTest.cs
app/SearchApi/BcGov.Fams3.Utils/BcGov.Fams3.Utils.csproj
app/SearchApi/BcGov.Fams3.Utils/String/StringExtension.cs

- update util, add toSHA1 static function to string
Tested locally

update util, add toSHA1 static function to string

---

app/SearchApi/BcGov.ApiKey.Middleware.Test/ApiKeyMiddlewareTest.cs
app/SearchApi/BcGov.ApiKey.Middleware/ApiKeyMiddleware.cs
app/SearchApi/BcGov.ApiKey.Middleware/BcGov.ApiKey.Middleware.csproj

- https://justice.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=3441&selectedIssue=FAMS3-3247
Tested locally and unit tests.

change to 2 layer authentication 

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj

update apikey lib version

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Constants.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/BankInfo/SSG_Asset_BankingInformation.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/RealEstate/SSG_Asset_RealEstateProperty.cs

- Fix could not locate for real estate and bank info
Tested locally

fix cnl issue

---

app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs

add more logs

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs

_logger.LogInformation(HttpContext.Request.Host.Host);

log - dynadatpr

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_SearchRequest_Test.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestStatusCode.cs

- FAMS3-3203 dynadaptor: in creating the sr, if it gets time out. Dyandatpor needs to system Cancel this SR.
Tested locally

In creating the sr, if it gets time out. Dyandatpor needs to system Cancel this SR

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs

- add cornet information source

add Cornet information source

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

update on date of birth

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyResponseControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyResponseController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Models/Acknowledgement.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Models/SearchResponseReady.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/APICall/APICallStatusCode.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/APICall/SSG_APICall.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/SearchRequest/NotificationAcknowledged.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchRequest.Adaptor.Test/Consumer/NotificationAcknowledgedConsumerTest.cs
app/SearchApi/SearchRequest.Adaptor.Test/FakeSearchRequestEvent.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Consumer/NotificationAcknowledgedConsumer.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/ServiceCollectionExtensions.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- FAMS3-3241: dynadaptor: add endpoint for receiving SUCCESS ack and upload to Dynamics.
- -FAMS3-3429: Add ApiCallGuid to response and Save response in Redis

response acknowledgement

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Employment.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

- https://justice.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=3441&view=detail&selectedIssue=FAMS3-3287
Tested locally

groupID upload and contract

---

app/SearchApi/BcGov.Fams3.Redis.Test/CacheServiceTest.cs
app/SearchApi/BcGov.Fams3.Redis/BcGov.Fams3.Redis.csproj
app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs

add expiry in redis

---

app/SearchApi/BcGov.Fams3.Redis.Test/CacheServiceTest.cs
app/SearchApi/BcGov.Fams3.Redis/BcGov.Fams3.Redis.csproj
app/SearchApi/BcGov.Fams3.Redis/ICacheService.cs

add expiry to redis savestring

add expiry to redis savestring

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs

- Deal with fams2 jca completed events
Tested with unit tests

Jca/fams2 : deal with fams2 jca events

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs

- deal with completed event for results from fams2 jca files.
Tested with unit tests

for fams2 jca: get the result from fams2 jca file

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs

- add corrections mapping to dynamics

update cornet mapping

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

-to be safe, just make sure the code is the same as working one
Tested with unit tests

to be safe,

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs

- probably won't be problem, but to be safe, just make things as original one.
Unit tests

to be safe

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs

-add JCA DOB and Gender
Unit tests

add jac Dob and gender

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/DynamicsAdapter.Web.Test.csproj
app/DynamicsAdapter/DynamicsAdapter.Web.Test/Health/DynamicsHealthCheckTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Health/DynamicsHealthCheck.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/ProviderProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Fams3Adapter.Dynamics.Test.csproj
app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/OptionSets/StatusReasonServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Keys.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/OptionSets/Models/BankAccountTypeOptionSet.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/OptionSets/OptionSetService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/PersonRelationType.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/TypeService.cs
app/SearchApi/AgencAdapter.Sample.Test/AgencAdapter.Sample.Test.csproj
app/SearchApi/BcGov.ApiKey.Middleware.Test/ApiKeyMiddlewareTest.cs
app/SearchApi/BcGov.ApiKey.Middleware.Test/BcGov.ApiKey.Middleware.Test.csproj
app/SearchApi/BcGov.ApiKey.Middleware/ApiKeyMiddleware.cs
app/SearchApi/BcGov.ApiKey.Middleware/BcGov.ApiKey.Middleware.csproj
app/SearchApi/BcGov.Fams3.Redis.Test/BcGov.Fams3.Redis.Test.csproj
app/SearchApi/BcGov.Fams3.Utils.Test/BcGov.Fams3.Utils.Test.csproj
app/SearchApi/SearchAdapter.Sample.Test/SearchAdapter.Sample.Test.csproj
app/SearchApi/SearchApi.Core.Test/SearchApi.Core.Test.csproj
app/SearchApi/SearchApi.Web.Test/SearchApi.Web.Test.csproj
app/SearchApi/SearchRequest.Adaptor.Test/SearchRequest.Adaptor.Test.csproj

-exclude health for ApiKey protection
Unit tests

Feature/health check/no apikey

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
app/SearchApi/SearchApi.Web/DeepSearch/Registry.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-3494

mapping error fix

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchRequest_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

- The middle name and other name is not mapped to Search Request, which is unacceptable.

fix missing names

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs

-FAMS3-3500(deal with appending notes from fmep, only show new appended string)
Tested with unit tests

when appending notes, need to hightlight

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchCompleted.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchCompletedJCA.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/SearchAdapter.Sample/SearchRequest/PersonSearchEventSample.cs
app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
app/SearchApi/SearchApi.Core.Test/Fake/FakePersonSearchCompletedJCA.cs
app/SearchApi/SearchApi.Web/Search/PersonEventConsumer.cs
app/SearchApi/SearchApi.Web/Startup.cs

add new queue for jca processing

add new queue for jca processing

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/ProviderProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Types/InformationSourceType.cs
app/SearchApi/SearchApi.Web/DeepSearch/Registry.cs

- for moh 3 different dps
Tested locally

for moh 3 different dps

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Constants.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

-should not show out of province in phone number.  FAMS3-3519

out of province removed from phone number

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs

- integration test, email message , address duplicate
Tested locally

Fix/email message, address duplication

---

app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonFound.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json

- dealing with icbc duplicate person in the same result
Tested locally

code for delaying in uploading same person

---

app/DynamicsAdapter/DynamicsAdapter.Web/Keys.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonFound.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json

fix icbc duplicates

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs

fix append notes

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/DynamicsEntity.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

- https://justice.gov.bc.ca/jira/browse/FAMS3-3556
- use is_primary to filter out person sought (update failure)

dynadapter fix

---

app/SearchApi/BcGov.Fams3.Redis/DependencyInjection/IServiceCollectionExtensions.cs
app/SearchApi/SearchApi.Web/appsettings.json
docker-compose.yml

Redisconfiguration has settings for retry, updated the settings for Idistributed cache
- https://justice.gov.bc.ca/jira/browse/FAMS3-3535

add redis timeout retry to settings

---

app/SearchApi/SearchApi.Web/Configuration/QueueRateLimit.cs
app/SearchApi/SearchApi.Web/Startup.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs
app/SearchApi/SearchRequest.Adaptor/appsettings.json

-Performance issue, retry creation SR.

throttle for autoSearch, and fix bug in retry creation SR.

---

app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/Fams3Adapter.Dynamics.Test.csproj
app/DynamicsAdapter/Fams3Adapter.Dynamics/Fams3Adapter.Dynamics.csproj

- make odata version consistence

correct odata version

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

-Revert this change as JCA fams2 uploading file issue needs to go to master firstly,

Revert "Fix/error queue (#532)"

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs

-If jca result is for fams2 search request, the searchApi cannot be found. should deal with this situation.

fix Fams2 JCA file upload problem.

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- Queue error processing
- searchApi name mapping

for fmep uat

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs

- Correct the rejected Update message format
Tested locally.

reject reason correct format

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs

- fams-3742-stop creating employment contact records
Tested locally.

fams-3742-stop creating employment contact records

---

app/SearchApi/SearchRequest.Adaptor/Configuration/QueueRateLimit.cs
app/SearchApi/SearchRequest.Adaptor/Startup.cs

- add rate configuration for request api
Tested locally

add rate configuration

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
app/SearchApi/SearchApi.Web/Program.cs
app/SearchApi/SearchApi.Web/appsettings.json
app/SearchApi/SearchRequest.Adaptor/Consumer/NotificationAcknowledgedConsumer.cs
app/SearchApi/SearchRequest.Adaptor/Consumer/SearchRequestOrderedConsumer.cs
app/SearchApi/SearchRequest.Adaptor/Program.cs
app/SearchApi/SearchRequest.Adaptor/appsettings.json

- FAMS3-3759- Improve Logging of Services

FAMS3-3759- Improve Logging of Services

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs
app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs
app/SearchApi/SearchApi.Web/Notifications/WebHookNotifierSearchEventStatus.cs
app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs

* change to openshift trigger accept notification - create sr
* accept event refactor
* autosearch, error queue
* autosearch , webhook error, put into error queue.
* move submit to queue out
* update unit tests
* update unit tests
Co-authored-by: PeggyZhangNtt <190728@nttdata.com>

Refactor/accept event (#543)

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

- change person hash data detection - - work around
Tested locally

change person hash data detection - work around

---

app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Core/Configuration/RetryConfiguration.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/DependencyInjection/IServiceCollectionsExtensions.cs

- change prefetch to be configurable
Tested locally

change prefetch to be configurable

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/AutoCloseSearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Updated to gracefully fail on exception when processing autoclose list

Updated to include message body(media type) which is in the token.

---

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/AutoCloseSearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

reverted previous change.

---

app/DynamicsAdapter/DynamicsAdapter.Web/ApiGateway/ApiGatewayHandler.cs
app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/AutoCloseSearchRequestJob.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Updates to fix the broken Auto close calls

---

app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestServiceTest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Updated to filter out any SR which are already autoclosed.

---

openshift/templates/jaeger-aio.dc.yaml
openshift/templates/jaeger.dc.yaml
openshift/templates/rabbitmq.dc.yaml

- Changing Service Type to something more appropriate for our current project use cases on OpenShift side. [FAMS3-3885] has detail problem statement. 
Will be tested after PR review and merge.

[FAMS3-3885] Removing Unsupported ServiceType

---

.github/workflows/main_buildimage.yml
.github/workflows/main_promoteimage.yml
app/NuGet.config
gitops/projectpathmapping.json

added s2i image creation workflow files
- Changes made for s2i image creation workflow files related to Jenkins replacement
Tested with local files and forked repo

added s2i image creation workflow files

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs

FAMS3-4108: Adding Agency Cod from mapped entity to reslover.

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Resolvers.cs

Reverts bcgov/fams3#602
This field will be exposed on the search api under JcaPerson instead.

Revert "FAMS3-4108: Adding Agency Cod from mapped entity to reslover."

---

app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/JCAPerson.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/Person.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/TaxIncomeInformation.cs
app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj

FAMS-4108:  Required Search API updates for getting and setting tax info

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/TaxIncomeInformation/SSG_Taxincomeinformation.cs

- Loading new fields in Person Search
- Unloading returned Tax Info to Dynamics.

FAMS3-4108 Dynadapter changes related to Tax Info.

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs

Fams-4108: Update DateTimeOffset to Map as DateTime

---

app/DynamicsAdapter/Fams3Adapter.Dynamics/TaxIncomeInformation/SSG_Taxincomeinformation.cs

FAMS-4108:  Updated Tax info with the proper type.

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/TaxIncomeInformation/SSG_Taxincomeinformation.cs

FAMS-4108: Updates namespace for TaxIncomeInformation

---

app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/TaxIncomeInformation/SSG_Taxincomeinformation.cs

FAMS 4108: Removed ssg_datadate from TaxInfo already in base class.

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs

Removed all field excepted ssg_name for testing

---

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfile_SearchResponse_Test.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
app/DynamicsAdapter/Fams3Adapter.Dynamics/TaxIncomeInformation/SSG_Taxincomeinformation.cs

Updated with additional exception handling and mapping for tax info on Search Result. 

---

.github/workflows/dotnetcore.yml
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

Fix code missing from last merge
Also, fix pipeline by adding correct openssl version before clean step

FAMS3-4147 fix last merge by adding missing code

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json

map other name and middle name from tax response instead of using jca person names

FAMS3-4222 map other name and middle name from tax response 

---

.github/workflows/main_promoteimage.yml
app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs

- Update parameter for runs-on to fix error.
- [x ] Bug fix (non-breaking change which fixes an issue)

Update runner to ubuntu-latest in promote image workflow

---

.github/workflows/main_promoteimage.yml

Fix: Ubuntu-latest for image tagging

---

.github/workflows/dotnetcore.yml

- FAMS3-4122
Gihub actions adjustments

FAMS3-4122 github actions .NET Upgrade 3.1 to 8.0

---

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj
app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs
app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SSG_SearchApiRequest.cs
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj
app/SearchApi/BcGov.Fams3.SearchApi.Contracts/Person/JCAPerson.cs

- FAMS3-4237 JCA - Update Outgoing Daily XML batch file

FAMS3-4237 JCA - Update Outgoing Daily XML batch file

---

app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json
app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs

FAMS3-4289 minor logger changes
