app/SearchApi/SearchApi.Web.Test/Search/MatchFoundConsumerTest.cs, app/SearchApi/SearchApi.Web/Search/MatchFoundConsumer.cs, app/SearchApi/SearchApi.Web/Startup.cs
* Search Api `MatchFoundConsumer` to consume result from adapters
=> Search Api must subscribe to MatchFound Events

.github/workflows/dotnetcore.yml
First cut at running unit tests through Github actions. This will build and test both the SearchApi and DynamicsAdapter
=> Create Github action for unit tests

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchRequest/SearchRequestJobTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs, app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json, app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs, app/SearchApi/SearchApi.Web/People/PeopleController.cs
This PR includes the following proposed changed:
- SearchApi support a new header `X-RequestId` to accept an id generated by the client for a given search request.
Locally with Docker
this PR fixes jira ticket: **FAMS3-613**
=> Feature/search api/add request

docker-compose.yml
* Set up webHooks for local `docker-compose` configuration
The response is now sent back to the dynamics adapter via webhooks:
Locally using docker
=> Configuring Dynamics Adapter callback

app/SearchApi/SearchAdapter.ICBC/Startup.cs, app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs, app/SearchApi/SearchApi.Core.Test/SearchApi.Core.Test.csproj, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchEvent.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchFailed.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchRejected.cs, app/SearchApi/SearchApi.Core/Adapters/Middleware/PersonSearchObserver.cs, app/SearchApi/SearchApi.Core/Adapters/Models/PersonSearchFailedEvent.cs
This PR includes the following proposed changed:
- A new `PersonSearch` Observer that report on adapter failures to the `SearchApi`
The Blue line represents the change:
this PR fixes jira ticket: **FAMS3-779**
=> Publish a PersonSearchFailed Message when Adapter Execution is failing

README.md, app/SearchApi/SearchAdapter.ICBC.Test/SearchRequest/SearchRequestConsumerTest.cs, app/SearchApi/SearchAdapter.ICBC/SearchRequest/SearchRequestConsumer.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchAccepted.cs, app/SearchApi/SearchApi.Core/Adapters/Models/DefaultPersonSearchAccepted.cs
- A new `PersonSearchAccepted` event sent when the adapter search pass the validation
Architecture Change are represented  with the blue line:
this PR fixes jira ticket: **FAMS3-778**
=> Publish a personSearchAccepted message when validation succeed

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceAddEventTest.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiEvent/SSG_SearchApiEvent.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
- A new function for the `SearchApiRequestService` to add a new event.
- A new endpoint in `PersonSearchController` to receive notifications
Architecture change:
Locally, with docker connected to FAMS3 dev instance
this PR fixes jira ticket: **FAMS3-771**
=> Add a new function in SearchApiService to create a new status report

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchApiRequest/SearchApiRequestServiceGetLinkedSearchRequestIdAsyncTest.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchApiRequest/SearchApiRequestService.cs
- use the `searchApiRequestId` as the main driver of the search
Local + Docker with Dynamics
this PR fixes jira ticket: **FAMS3-790**
=> Change workflow to use the SearchApiRequest Id instead of the SearchRequestId

app/SearchApi/SearchApi.Web/People/Identifier.cs, app/SearchApi/SearchApi.Web/People/IdentifierType.cs, app/SearchApi/SearchApi.Web/People/IdentifierTypeEnum.cs
- remove int value of the enum for improving swagger documentation
Locally
this PR fixes jira ticket: **FAMS3-803**
=> SearchApi should expose Enum as String not int

app/SearchApi/SearchAdapter.ICBC.Test/SearchRequest/SearchRequestConsumerTest.cs, app/SearchApi/SearchAdapter.ICBC/SearchRequest/SearchRequestConsumer.cs, app/SearchApi/SearchAdapter.ICBC/Startup.cs, app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/AdapterEvent.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchAccepted.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchEvent.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchFailed.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchOrdered.cs, app/SearchApi/SearchApi.Core/Adapters/Contracts/PersonSearchRejected.cs, app/SearchApi/SearchApi.Core/Adapters/Middleware/PersonSearchObserver.cs, app/SearchApi/SearchApi.Core/Contracts/ExecuteSearch.cs, app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs, app/SearchApi/SearchApi.Web/People/PeopleController.cs, app/SearchApi/SearchApi.Web/Startup.cs
This PR includes the following change:
- Send a `PersonSearchOrdered` event for the adapters to consume
- Consume `PersonSearchOrdered` on the SearchAdapters
Architecture Change:
.
this PR fixes jira ticket: **FAMS3-770**
=> Publish new PersonSearchOrdered events to all adapters

README.md, app/SearchApi/SearchApi.Web.Test/Configuration/SearchApiOptionsTest.cs, app/SearchApi/SearchApi.Web.Test/Notifications/WebHookNotifierSearchStatusTest.cs, app/SearchApi/SearchApi.Web/Configuration/SearchApiOptions.cs, app/SearchApi/SearchApi.Web/appsettings.json, docker-compose.yml
- Removing the Event from the webHook configuration as not in use.
this PR fixes jira ticket: **FAMS3-840**
=> Remove EventName from webHooks Configuration

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
This is to process Person Search Completed event sent from searchApi.
We ignore payload right now. Will deal with correct payload in another pr.
tested locally and connected to dynamic dev server.
this PR fixes jira ticket: FAMS-823
=> Process completed event in PersonSearch controller for dynaAdaptor

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchCompleted.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs
This is to fix problem 871. Actually, the PersonSearchCompleted include member should be named MatchedPerson
Tested on local machine
this PR fixes jira ticket: FAMS-871
=> fix ticket -871

app/DynamicsAdapter/DynamicsAdapter.Web.Test/ApiGateway/ApiGatewayHandlerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/ApiGateway/ApiGatewayHandler.cs
- Adding support for QueryString and path for the ApiGatewayHandler
Local Docker  + Unit Tests
this PR fixes jira ticket: **FAMS3-880**
=> Adding support for basePath + QueryString apiGatewayHandler

app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestAutoMapperProfile.cs, app/SearchApi/SearchAdapter.Sample/SearchRequest/SearchRequestConsumer.cs
DynAdapter can map the returned suppliedBy to sourceText in ssg_identifier.
tested on local machine
this PR fixes jira ticket: FAMS-885
=> DynAdapter can map the returned suppliedBy to sourceText in ssg_identifier.

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Mapping/MappingProfileTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/MappingProfile.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/Person.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs, app/DynamicsAdapter/DynamicsAdapter.Web/searchApi.openapi.json, app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs
We should not manually modify the generated searchApi.openapi.json. So, dynadapter should use auto-generated searchApi.openapi.json.
Tested locally
this PR fixes jira ticket: FAMS-952
=> dynAdaptor should use auto generated json api spec.

app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs, app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs, app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs, app/SearchApi/SearchApi.Web/Program.cs, app/SearchApi/SearchApi.Web/SearchApi.Web.csproj, app/SearchApi/SearchApi.Web/appsettings.json
- Add [serilog](https://serilog.net/) as the default logger
- Fix the issue with the api
Locally with VS
this PR fixes jira ticket: **FAMS3-1060*
=> Add SeriLog as default logger for search APi

.gitignore, .s2i/bin/assemble.sh, openshift/.pipeline/Jenkinsfile, openshift/docker-images/dotnet-3.0/Dockerfile, openshift/templates/dynamics-adapter.bc.yaml, openshift/templates/dynamics-adapter.dc.yaml, openshift/templates/icbc-rest-adapter.bc.yaml, openshift/templates/sample-adapter.bc.yaml, openshift/templates/search-api.bc.yaml
This PR has the changes necessary to pull the private packages from our Artifactory instance. The specific nuget configurations are contained in a ConfigMap on the frjeow-tools namespace.
=> Pull Packages from Artifactory in build

.s2i/bin/assemble.sh
There is an issue with CoreFX on RHEL images where it is looking in the wrong location for certificate bundles, this is attempting to fix that issue.
=> Soft link of certificate locations for s2i assemble

openshift/templates/icbc-web-adapter.bc.yaml
- REVERTING: Changing build to not use default socket library in attempt to fix Artifactory issues.
=> Stability issues and fixes

openshift/templates/icbc-web-adapter.bc.yaml
This is being done to avoid pulling from Nexus or Artifactory
=> Remove dotnet restore config file reference

app/SearchApi/BcGov.Fams3.Redis/Model/SearchRequest.cs, app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchOrdered.cs, app/SearchApi/SearchAdapter.Sample.Test/SearchRequestConsumerTest.cs, app/SearchApi/SearchApi.Core.Test/Adapters/Middleware/PersonSearchObserverTest.cs, app/SearchApi/SearchApi.Web.Test/Messaging/DispatcherTest.cs, app/SearchApi/SearchApi.Web.Test/People/PeopleControllerTest.cs, app/SearchApi/SearchApi.Web.Test/People/PersonSearchRequestTest.cs, app/SearchApi/SearchApi.Web/Messaging/Dispatcher.cs, app/SearchApi/SearchApi.Web/People/PeopleController.cs, app/SearchApi/SearchApi.Web/People/PersonSearchRequest.cs
- FAMS-1902([SEARCH API] - Add fileId to the PersonSearchRequest and transfer it to webAdapters.)
Tested locally
=> Add fileId to searchApi

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
- FAMS3-2201(dynadapter-get GUID from Redis cache for source Identifier)
=> get matched ssg_identifier from cache.

app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj, docker-compose.yml
Updated docker compose and use library for redis in dynadapter. This is a temporary fix to ensure docker-compose works for local development.
We need to fix nexus / artefactory repository package
=> fix  docker compose

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchFinalized.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/Models/PersonSearchStatus.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/PersonSearchController.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Program.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchRequest/SearchRequestJob.cs, app/DynamicsAdapter/DynamicsAdapter.Web/appsettings.json, app/DynamicsAdapter/DynamicsAdapter.sln, app/SearchApi/BcGov.Fams3.SearchApi.Contracts/BcGov.Fams3.SearchApi.Contracts.csproj, app/SearchApi/BcGov.Fams3.SearchApi.Contracts/PersonSearch/PersonSearchReceived.cs, app/SearchApi/BcGov.Fams3.SearchApi.Core/BcGov.Fams3.SearchApi.Core.csproj, app/SearchApi/SearchAdapter.Sample.Test/SearchResultConsumerTest.cs
-FAMS3-2248 (dynadapter-save fileID, seq id and searchApi guid to cache. use fileID and seqID as id in contract.)
Tested locally
=> Refactor/cleanup radis, make searchRequestKey works in dynadapter personSearchController.

app/DynamicsAdapter/DynamicsAdapter.Web.Test/Register/SearchRequestRegisterTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Register/SearchRequestRegister.cs
- this is a bug found during sprint20 review planning
Tested locally
=> fix issue about sourceIdentifier filtering. We should not compare issuedBy.

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestServiceTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Models/SearchRequestEvent.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/Models/SearchRequestSubmitted.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_SearchRequest_Test.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestStatusCode.cs, app/SearchApi/BcGov.Fams3.SearchApi.Contracts/SearchRequest/SearchRequestEvent.cs, app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs, app/SearchApi/SearchRequest.Adaptor.Test/Publisher/SearchRequestEventPublisherTest.cs, app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs, app/SearchApi/SearchRequest.Adaptor/Publisher/Models/ProviderProfile.cs, app/SearchApi/SearchRequest.Adaptor/Publisher/Models/SearchRequestFailedEvent.cs, app/SearchApi/SearchRequest.Adaptor/Publisher/Models/SearchRequestRejectedEvent.cs, app/SearchApi/SearchRequest.Adaptor/Publisher/Models/SearchRequestSubmittedEvent.cs, app/SearchApi/SearchRequest.Adaptor/Publisher/SearchRequestEventPublisher.cs
-FAMS3-2461 (DynaAdapter] check if search request is not - In analysis - update SR to cancel)
-FAMS3-2504 (Dynadapter send submitted response back to request adaptor.)
Tested locally with unit tests.
=> submitted event and cancel search request

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestServiceTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_SearchRequest_Test.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SSG_SearchRequest.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
- FAMS3-2548(for searchRequest, if "update" provided information is different, do update the entity.)
- FAMS3-2550(for notes, if it is different than original one, add notes to notes Entity.)
- FAMS-2551(for informationRequested, if it is different than original ones, add the new ones.)
Tested Locally and added new unit tests
=> update search request - search request entity

app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Create_Cancel_Test.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/SearchAgency/AgencyRequestService_Update_Test.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Contructors.cs, app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestService.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics.Test/SearchRequest/SearchRequestService_Person_Test.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Address/SSG_Address.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Employment/SSG_Employment.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Identifier/SSG_Identifier.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Name/SSG_Alias.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Person/SSG_Person.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/Phone/SSG_PhoneNumber.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/RelatedPerson/SSG_RelatedPerson.cs, app/DynamicsAdapter/Fams3Adapter.Dynamics/SearchRequest/SearchRequestService.cs
- FAMS3-2569(add CreateByAgency and corresponding logic to searchRequest related entities.)
=> add createdByAgency flag for related entities

app/DynamicsAdapter/DynamicsAdapter.Web/Startup.cs, app/SearchApi/SearchApi.Web/Startup.cs, app/SearchApi/SearchRequest.Adaptor/Startup.cs
- FAMS3-2138([DynaAdapter - [DynamicsAdapter.Web]] The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'.)
Tested locally
=> add nosniff http header to all httpresponse

app/DynamicsAdapter/DynamicsAdapter.Web/SearchAgency/AgencyRequestController.cs, app/SearchApi/SearchRequest.Adaptor.Test/Consumer/SearchRequestOrderedConsumerTest.cs, app/SearchApi/SearchRequest.Adaptor.Test/Notifier/SearchRequestNotifierTest.cs, app/SearchApi/SearchRequest.Adaptor/Consumer/SearchRequestOrderedConsumer.cs, app/SearchApi/SearchRequest.Adaptor/Notifier/SearchRequestNotifier.cs, app/SearchApi/SearchRequest.Adaptor/Startup.cs, app/SearchApi/SearchRequest.Adaptor/appsettings.json
- request Api: when dynadatpor failed in creating SR, we need retry to re-create SR.
=> Feature/3204-request Api: when dynadatpor failed in creating SR, we need retry to re-create SR.

app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/PersonSearchControllerTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web.Test/PersonSearch/SearchResultServiceTest.cs, app/DynamicsAdapter/DynamicsAdapter.Web/Mapping/Converters.cs, app/DynamicsAdapter/DynamicsAdapter.Web/PersonSearch/SearchResultService.cs
- Processing XML files with tax information: generate JCA person details and JCA tax info details:
- Processing XML files with no tax info: generate only JCA person details:
1.- Request to client for XML files with/without tax information.
2.- Connect to FAMS3 Test on OCP and retrieve the following commands:
```
GET JCA_CtrlCode_ZB61Z4
GET JCA_008819_00012402_PersonSought
GET dyna_008819_00012402
```
3.- Setup your local to point to Dynamics on Test
4.- Set local Redis with the data retrieved from Test
5.- Update FileWatcherJob to read XML file
6.- Run SearchApi, DynamicsAdapter and FileAdapter
7.- Check fileAdapter is sending message to …
=> FAMS3-4222: Tax Income Info - OT xml processing should not merge Person Sought

.github/workflows/main_promoteimage.yml
-Downgrade ubuntu to original version - Ubuntu-latest points to Ubuntu 22.04 no longer include .NET Core 3.1 pre-installed. Issues in compatbility with .NET Core 3.1
-Ubuntu-20.04 is older and still compatible with .NET Core 3.1 and its dependencies, so builds and restores work as expected.
- [ X] Bug fix (non-breaking change which fixes an issue)
=> Downgrade ubuntu to original version
